title: Project

files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
      width: 1/3
    altText:
      label: Texte alternatif
      type: textarea
      width: 1/3
      required: true
    source:
      label: Source
      type: text
      width: 1/3

pages: false

fields:
  featuredProject:
    label: Featured Project
    required: true
    type: toggle
    text: yes/no

  title:
    label: Title
    type:  text
    width: 3/4
    required: true

  year:
    label: Year
    type:  text
    width: 1/4

  smalldescription:
    label: Small Description
    type:  textarea
    width: 1/2
    required: true

  tags:
    label: Tags
    type: tags
    width: 1/2
    required: true

  descriptionparagraphs:
    label: Description du projet
    type: structure
    fields:
      singleparagraph:
        label: Paragraphe simple
        type: textarea
      associatedimage:
        label: Illustration
        type: image
      alternativetext:
        label: Texte alternative
        type: text
      figcaptionimage:
        label: Légende (figcaption)
        type: textarea

  categories:
    label: Categories
    type: checkboxes
    options:
      game: Game
      iot: IoT
      installation: Intallation
      datavis: Datavisualisation
      fictionDesign: Design fiction
      interactionDesign: Interaction design
      graphicDesign: Graphic design
      ux: User Experience
      ui: User Interface
      web: Webdesign
      dev: Development

  thematics:
    label: Thematics
    type: checkboxes
    options:
      writing: writing
      talking: talking
      rhetorics: rhetorics
      autocomplete: autocomplete
      democracy: democracy
      socialHacking: social hacking

  maindescription:
    label: Main Description
    type:  textarea
    required: true

  illustration_0:
    label: Illustration 1
    type:  image

  description_1:
    label: Description Part 2
    type: textarea

  illustration_1:
    label: Illustration 2
    type:  image

  description_2:
    label: Description Part 3
    type: textarea

  website:
      label: Website
      type: url
      width: 1

  video:
    label: Video
    type: url
    width: 1/2

  press:
      label: Press
      type: structure
      width: 1/2
      fields:
          newspaper:
            label: Name of newspaper, event
            type: text
          url:
            label: lien
            type: url
          language:
            label: language
            type: text
          artcl:
            label: Name of article
            value: text

  links:
      label: Additional links
      type: structure
      width: 1/2
      fields:
        type:
          label: Type
          type: text
        url:
          label: Lien
          type: url


  misc:
      label: Other...
      type: textarea
