title: Project

files:
  sortable: true
  fields:
    caption:
      label: Caption
      type: textarea
      width: 1/3
    altText:
      label: Texte alternatif
      type: textarea
      width: 1/3
      required: true
    source:
      label: Source
      type: text
      width: 1/3

pages: false

fields:
  title:
    label: Title
    type:  text
    width: 3/4
    required: true

  year:
    label: Year
    type:  text
    width: 1/4

  smalldescription:
    label: Small Description
    type:  textarea
    width: 1/2
    required: true

  tags:
    label: Tags
    type: tags
    width: 1/2
    required: true

  categories:
    label: Categories
    type: checkboxes
    options:
      web: web
      game: game
      iot: iot
      datavis: datavisualisation
      fictionDesign: fiction design
      interactionDesign: interaction design
      graphicDesign: graphic design
      publishing: publishing

  thematics:
    label: Thematics
    type: checkboxes
    options:
      writing: writing
      talking: talking
      rhetorics: rhetorics
      autocomplete: autocomplete
      democracy: democracy
      socialHacking: social hacking

  maindescription:
    label: Main Description
    type:  textarea
    required: true

  website:
      label: Website
      type: url
      width: 1

  press:
      label: Press
      type: url
      width: 1/2

  video:
        label: Video
        type: url
        width: 1/2

  misc:
      label: Other...
      type: textarea
